# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpubsub.proto\"E\n\x0ePublishRequest\x12\x13\n\x0b\x63hannelName\x18\x01 \x01(\t\x12\x11\n\tdelayTime\x18\x02 \x01(\x03\x12\x0b\n\x03msg\x18\x03 \x01(\t\":\n\x10SubscribeRequest\x12\x13\n\x0b\x63hannelName\x18\x01 \x01(\t\x12\x11\n\tdelayTime\x18\x02 \x01(\x03\"\x17\n\x08Response\x12\x0b\n\x03msg\x18\x01 \x01(\t2`\n\x06PubSub\x12\'\n\x07Publish\x12\x0f.PublishRequest\x1a\t.Response\"\x00\x12-\n\tSubscribe\x12\x11.SubscribeRequest\x1a\t.Response\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pubsub_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PUBLISHREQUEST._serialized_start=16
  _PUBLISHREQUEST._serialized_end=85
  _SUBSCRIBEREQUEST._serialized_start=87
  _SUBSCRIBEREQUEST._serialized_end=145
  _RESPONSE._serialized_start=147
  _RESPONSE._serialized_end=170
  _PUBSUB._serialized_start=172
  _PUBSUB._serialized_end=268
# @@protoc_insertion_point(module_scope)
